filetype plugin indent on

"Disable arrow-keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <right> <nop>
imap <left> <nop>
imap <up> <nop>
imap <down> <nop>

"Map j+k k+j to go back to command mode
inoremap jk <ESC>
inoremap kj <ESC>

"Map Ctrl+key to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

map <C-p> :e!<CR>

" Remap 0 to first non-blank character
map 0 ^

"Treat long lines as break lines
map j gj
map k gk

" Keep selection after index
vnoremap < <gv
vnoremap > >gv

"Color related configs
syntax enable                   
set number
" Disable start screen
set shortmess+=aAIsT
set cursorline
" Set column ruler according to file type
set colorcolumn=100
au BufNewFile,BufRead *.jazz set filetype=c
au BufNewFile,BufRead *.japp set filetype=c
au BufNewFile,BufRead *.jahh set filetype=c

"Search options
set ignorecase  "Ignore case when searching
set incsearch   "Instant search

"Command listing
set wildmenu
set path+=**

"Turn most backup options off
set nobackup
set nowb
set noswapfile

set ttyfast

set smarttab

"1 tab = 2 spaces
set shiftwidth=2
set tabstop=2
set expandtab " tab to spaces

set ai "Auto indent
set si "Smart indent

set lazyredraw

set mat=2
set encoding=utf-8
set showmatch
set nocompatible
set mouse=a
