" Check if the plugin manager is installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

""""""""""""""Plugin manager""""""""""""""" 
call plug#begin()

Plug 'scrooloose/nerdtree'
Plug 'ervandew/supertab'
Plug 'itchyny/lightline.vim'
Plug 'tomasiser/vim-code-dark'
Plug 'w0rp/ale'
Plug 'pangloss/vim-javascript'          "javascript improved syntax highlighting
Plug 'leafgarland/typescript-vim'       "support for typescript

call plug#end()            
filetype plugin indent on    
""""""""""""""""""""""""""""""""""""""""""""""""""" 
"Map j+k k+j to go back to command mode
inoremap jk <ESC>
inoremap kj <ESC>

"Lightline
let g:lightline = {
      \ 'colorscheme': 'material',
      \ }

"Bind <C-o> to NERDTree
map <C-o> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let NERDTreeShowHidden=1

"Enter distraction-free mode
map <C-f> :Goyo 160x120<CR>

" Bind noh to <C-n>
map <C-n> :noh<CR> 

"Disable arrow-keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <right> <nop>
imap <left> <nop>
imap <up> <nop>
imap <down> <nop>

"Map Ctrl+key to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Remap 0 to first non-blank character
map 0 ^

"Treat long lines as break lines
map j gj
map k gk

" Keep selection after index
vnoremap < <gv
vnoremap > >gv

"Color related configs
colorscheme codedark
syntax enable                   " Enable syntax highlighting
set number
set shortmess+=aAIsT            " disable welcome screen

set laststatus=2

"Search options
set ignorecase  "Ignore case when searching
set incsearch   "Instant search

"Command listing
set wildmenu
set path+=**

"Turn most backup options off
set nobackup
set nowb
set noswapfile

"Update file when modified outside of vim
set autoread

"Use spaces instead of tabs
set expandtab

set ttyfast

"Fold idented code
"set foldmethod=indent
"set foldlevel=1

"Be smart when using tabs ;)
set smarttab

"1 tab = 4 spaces
set shiftwidth=4
set tabstop=4


set ai "Auto indent
set si "Smart indent

set lazyredraw "Keeps vim from redrawing the window so often

set mat=2
set encoding=utf-8
set showmatch
set nocompatible
