xrandr --dpi 140
xrdb ~/.Xresources.hidpi

export GDK_DPI_SCALE=1.1

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1.1

systemctl --user import-environment DISPLAY
xinput set-prop bcm5974 295 1
exec i3
