# Environment variables
export PATH=$HOME/bin:/usr/local/bin:/usr/local/platform-tools/:/usr/local/sicstus4.3.0/bin:$PATH

export ZSH=~/.oh-my-zsh

export EDITOR=vim
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Set this to "random" to load a random theme each time
ZSH_THEME="powernex"

# Update frequency
export UPDATE_ZSH_DAYS=7

# Enable command auto-correction.
ENABLE_CORRECTION="true"

# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# ssh-agent autostart
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-config
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-config)" >> null
fi
# export SSH_KEY_PATH="~/.ssh/rsa_id"

#Aliases
alias sicstus="rlwrap sicstus"
