#export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH=/home/miguel/.oh-my-zsh

# Set this to "random" to load a random theme each time
ZSH_THEME="lambda"

# Update frequency
export UPDATE_ZSH_DAYS=13

# Enable command auto-correction.
# ENABLE_CORRECTION="true"

# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Plugins dir: ~/.oh-my-zsh/plugins/*
# Custom plugins: ~/.oh-my-zsh/custom/plugins/
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='vim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"
